---
name: Authelia
version: dev
slug: authelia
url: https://www.authelia.com/
init: false
description: Authelia is an open-source authentication and authorization server
webui: http://[HOST]:[PORT:9091]
stage: experimental
arch:
  - aarch64
  - amd64
startup: application
ports:
  9091/tcp: 9091
ports_description:
  9091/tcp: Web interface
map:
  - share:rw
